require "arrays/array-semantics.k"
require "lvalues/runtime-lvalue-semantics.k"
require "member-declaration/runtime-member-declaration-semantics.k"
require "method-declaration/runtime-method-declaration-semantics.k"

module RUNTIME-SEMANTICS 
	imports ARRAY-SEMANTICS
	imports RUNTIME-LVALUE-SEMANTICS
	imports RUNTIME-MEMBER-DECLARATION-SEMANTICS
	imports RUNTIME-METHOD-DECLARATION-SEMANTICS

endmodule